// QUE SEA EL DUEÑO DE LOS ALMACENES DE VOTOS, ES DECIR QUE SE ENCARGUE DE DEPLOYARLOS Y CONTROLE CUANDO CIERRAN USANDO CHAINLINK FUNCTIONS

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;


contract Election {

}